version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.24
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.32
    - 14.14.34
    - 14.14.39
    - 15.0.0
  - dependency-name: postcss
    versions:
    - 8.2.12
    - 8.2.5
    - 8.2.7
  - dependency-name: "@angular/platform-browser-dynamic"
    versions:
    - 11.2.10
    - 11.2.11
    - 11.2.9
  - dependency-name: "@angular/forms"
    versions:
    - 11.2.10
    - 11.2.11
    - 11.2.9
  - dependency-name: "@angular/router"
    versions:
    - 11.2.10
    - 11.2.11
    - 11.2.9
  - dependency-name: "@angular/animations"
    versions:
    - 11.2.10
    - 11.2.11
    - 11.2.2
    - 11.2.9
  - dependency-name: core-js
    versions:
    - 3.10.1
    - 3.10.2
  - dependency-name: "@angular/compiler-cli"
    versions:
    - 11.2.10
    - 11.2.11
    - 11.2.9
  - dependency-name: "@angular/common"
    versions:
    - 11.2.10
    - 11.2.11
    - 11.2.9
  - dependency-name: "@angular/platform-browser"
    versions:
    - 11.2.10
    - 11.2.11
    - 11.2.9
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.2.4
  - dependency-name: "@babel/core"
    versions:
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.13
  - dependency-name: jasmine-core
    versions:
    - 3.7.0
  - dependency-name: karma
    versions:
    - 6.0.3
    - 6.0.4
    - 6.1.2
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.16
    - 7.13.0
    - 7.13.9
  - dependency-name: puppeteer
    versions:
    - 6.0.0
    - 7.0.0
    - 7.0.4
