dist: bionic

language: node_js
node_js:
  - "12"

addons:
  chrome: stable

services:
  - xvfb

cache:
  directories:
     - ./node_modules

before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost &

install:
  - npm install
  - npm install -g gulp-cli

script:
  - sudo -E env "PATH=$PATH" gulp test

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info -X fix
