version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.6
  cypress: cypress-io/cypress@3.3.0
  codecov: codecov/codecov@4.0.1
jobs:
  test:
    docker:
      - image: cimg/node:lts-browsers
    environment:
      CHROME_BIN: /usr/bin/google-chrome
    steps:
      - checkout
      - run: sudo apt-get update
      - browser-tools/install-browser-tools:
          chrome-version: 120.0.6099.62 # temporary, until https://github.com/CircleCI-Public/browser-tools-orb/issues/104 is fixed
      - run: google-chrome --version
      - restore_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - codecov/upload
  e2e:
     docker:
       - image: cimg/node:lts-browsers
     environment:
       CHROME_BIN: /usr/bin/google-chrome
     steps:
       - checkout
       - run: sudo apt-get update
       - browser-tools/install-browser-tools:
          chrome-version: 120.0.6099.62 # temporary, until https://github.com/CircleCI-Public/browser-tools-orb/issues/104 is fixed
       - run: google-chrome --version
       - cypress/install
       - restore_cache:
           key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
       - run:
           name: Install dependencies
           command: npm install
       - save_cache:
           key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
           paths:
             - "node_modules"
       - run:
           name: Run e2e tests
           command: npm run e2e

workflows:
  run-testing:
    jobs:
      - test
      - e2e
